package com._labor.fakecord.infrastructure.outbox.domain;

public enum OutboxEventType {
  USER_REGISTERED,
  USER_EMAIL_VERIFIED,
  USER_DELETED,
  USER_PROFILE_UPDATED,
  
  USER_CONNECTION_CREATED,
  USER_CONNECTION_DELETED, 

  CHANNEL_CREATED,
  CHANNEL_MEMBER_ADDED,
  CHANNEL_MEMBER_REMOVED,
  CHANNEL_RENAMED,

  SOCIAL_FRIEND_REQUEST_SENT,
  SOCIAL_FRIEND_REQUEST_DECLINED,
  SOCIAL_FRIEND_REQUEST_ACCEPTED,
  SOCIAL_FRIEND_REQUEST_CANCELLED,
  SOCIAL_FRIEND_REQUEST_IGNORED,
  SOCIAL_FRIENDSHIP_CREATED,
  SOCIAL_FRIENDSHIP_TERMINATED,
  SOCIAL_USER_BLOCKED,
  SOCIAL_USER_UNBLOCKED,

  MEDIA_ATTACHMENT_READY,
  MESSAGE_CREATED,

  SERVER_DELETED,
  SERVER_MEMBER_JOINED,
  SERVER_MEMBER_LEFT,
  SERVER_OWNERSHIP_TRANSFERRED,

  SERVER_RESTRICTION_APPLIED,
  SERVER_RESTRICTION_DEACTIVATED
}
