package com._labor.fakecord.infrastructure.outbox.domain;

public enum OutboxEventType {
  USER_REGISTERED,
  USER_EMAIL_VERIFIED,
  USER_DELETED,
  USER_PROFILE_UPDATED,
  USER_CONNECTION_CREATED,
  USER_CONNECTION_DELETED, 
  SOCIAL_FRIEND_REQUEST_SENT,
  SOCIAL_FRIEND_REQUEST_DECLINED,
  SOCIAL_FRIEND_REQUEST_ACCEPTED,
  SOCIAL_FRIEND_REQUEST_CANCELLED,
  SOCIAL_FRIEND_REQUEST_IGNORED,
  SOCIAL_FRIENDSHIP_CREATED,
  SOCIAL_FRIENDSHIP_TERMINATED,
  SOCIAL_USER_BLOCKED,
  SOCIAL_USER_UNBLOCKED
}
